name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Restore dependencies and add packages
      run: |
        dotnet restore
        dotnet add package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore --version 6.0.25
        dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore --version 6.0.25
        dotnet add package Microsoft.AspNetCore.Identity.UI --version 6.0.25
        dotnet add package Microsoft.EntityFrameworkCore.Abstractions --version 6.0.25
        dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 6.0.25
        dotnet add package Microsoft.EntityFrameworkCore.Tools --version 6.0.25
        dotnet add package Telerik.UI.for.AspNet.Core --version 2024.1.319

    - name: Build
      run: dotnet build
